config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]
  root to: 'influencers#index'

  get '/my_jobs', to: 'jobs#index'
  get '/baby_boomers', to: 'influencers#baby_boomers'
  get '/generation_x', to: 'influencers#generation_x'
  get '/millennials', to: 'influencers#millennials'
  get '/generation_z', to: 'influencers#generation_z'
  get '/all_influencers', to: 'influencers#index_complete'



  resources :influencers, only: [:index, :index_complete, :show, :baby_boomers, :generation_x, :millennials, :generation_z] do
    resources :jobs, only: [:index, :show, :create, :new] do
          patch :update_job_state, on: :member
      resources :reviews, except: [:new, :show, :update]
    end
  end

  resources :orders, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
  end
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController

  def index
    @generations = User.target_generations
  end

  def index_complete
    if params[:query].present?
      sql_query = "username ILIKE :query OR cast(media_type as text) ILIKE :query OR content_type ILIKE :query"
      # @influencers = User.all.where(sql_query, query: "%#{params[:query]}%")
      @influencers = User.all.where(role: 0).where(sql_query, query: "%#{params[:query]}%")
    else
      @influencers = User.all.where(role: 0)
    end
  end

  def show
    @influencer = User.find(params[:id])
  end

  ## Methods and routes for different categories of influencers

  def baby_boomers
    @influencers = User.all.where(role: 0, target_generation: 'baby_boomer')
  end

  def generation_x
    @influencers = User.all.where(role: 0, target_generation: 'generation_x')
  end

  def millennials
    @influencers = User.all.where(role: 0, target_generation: 'millennial')
  end

  def generation_z
    @influencers = User.all.where(role: 0, target_generation: 'generation_z')
  end
end

app/views/influencers/_index_complete.html.erb
  </br>
</br>
<div class="influencer-header">
  <h1 class="text-center">Our Influencers</h1>
</div>
<div class="container">
  <div class="wrapper-index">
    <div class="cards-container-my-orders">
      <div class="row">
        <% @influencers.each do |influencer| %>
        <div class="col-xs-12 col-sm-4 col-lg-3">
          <div class="card">
            <%= link_to influencer_path(influencer) do %>
            <div class="card-picture"
            style="background: url('<%= influencer.photo %>')">
            <div class="card-title">
              <p class="influencer-name text-center"><%= influencer.first_name.titleize %> <%= influencer.last_name.titleize %></p>
            </div>
            <div class="card-footer">
              <p class="influencer-mediatype"><%= influencer.media_type.titleize %> <br />
                <%= influencer.number_of_followers %> Followers</p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/influencers/baby_boomers.html.erb
<div class="wrapper">
  <%#= render 'shared/search_bar' %>
  <div class="influencer-header">
    <h1 class="text-center">Our Influencers</h1>
  </div>
  <div class="container">
    <div class="wrapper-index">
      <div class="cards-container-my-orders">
        <div class="row">
          <% @influencers.each do |influencer| %>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <div class="card">
              <%= link_to influencer_path(influencer) do %>
              <div class="card-picture"
              style="background: url('<%= influencer.photo %>')">
              <div class="card-title">
                <p class="influencer-name text-center"><%= influencer.first_name.titleize %> <%= influencer.last_name.titleize %></p>
              </div>
              <div class="card-footer">
                <p class="influencer-mediatype"><%= influencer.media_type.titleize %> <br />
                  <%= influencer.number_of_followers %> Followers</p>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/influencers/generation_x.html.erb
<div class="wrapper">
  <%#= render 'shared/search_bar' %>
  <div class="influencer-header">
    <h1 class="text-center">Our Influencers</h1>
  </div>
  <div class="container">
    <div class="wrapper-index">
      <div class="cards-container-my-orders">
        <div class="row">
          <% @influencers.each do |influencer| %>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <div class="card">
              <%= link_to influencer_path(influencer) do %>
              <div class="card-picture"
              style="background: url('<%= influencer.photo %>')">
              <div class="card-title">
                <p class="influencer-name text-center"><%= influencer.first_name.titleize %> <%= influencer.last_name.titleize %></p>
              </div>
              <div class="card-footer">
                <p class="influencer-mediatype"><%= influencer.media_type.titleize %> <br />
                  <%= influencer.number_of_followers %> Followers</p>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/influencers/generation_z.html.erb
<div class="wrapper">
  <%#= render 'shared/search_bar' %>
  <div class="influencer-header">
    <h1 class="text-center">Our Influencers</h1>
  </div>
  <div class="container">
    <div class="wrapper-index">
      <div class="cards-container-my-orders">
        <div class="row">
          <% @influencers.each do |influencer| %>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <div class="card">
              <%= link_to influencer_path(influencer) do %>
              <div class="card-picture"
              style="background: url('<%= influencer.photo %>')">
              <div class="card-title">
                <p class="influencer-name text-center"><%= influencer.first_name.titleize %> <%= influencer.last_name.titleize %></p>
              </div>
              <div class="card-footer">
                <p class="influencer-mediatype"><%= influencer.media_type.titleize %> <br />
                  <%= influencer.number_of_followers %> Followers</p>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/influencers/index.html.erb
<% if current_user.role == 'client' %>
<div class="container">
  <div class="wrapper-index">
    <div class="cards-container-my-orders">
      <%#= render 'shared/search_bar' %>
      <div class="row">
        <div class="target-header">
          <h1 class="text-center">Who do you want to target?</h1>
        </div>
        <% @generations.each do |generation| %>
        <div class="col-xs-12 col-sm-4 col-lg-3">
          <div class="target-card">
            <div class="target-card-picture">
              <div class="target-card-title">
                <% if generation[0] == 'baby_boomer' %>
                <h3 class="text-center">Baby Boomers</h3> 
                <% elsif generation[0] == 'generation_x' %>
                <h3 class="text-center"> Generation X</h3>
                <% elsif generation[0] == 'millennial' %>
                <h3 class="text-center"> Millennials </h3>
                <% else %>
                <h3 class="text-center"> Generation Z</h3>
                <% end %>
                <p class="influencer-name text-center"></p>
              </div>
              <div class="target-card-footer">

                <% if generation[0] == 'baby_boomer' %>
                <%= link_to("Select", "/baby_boomers" , class: 'button-target') %>
                <% elsif generation[0] == 'generation_x' %>
                <%= link_to("Select", "/generation_x" , class: 'button-target') %>
                <% elsif generation[0] == 'millennial' %>
                <%= link_to("Select", "/millennials" , class: 'button-target') %>
                <% else %>
                <%= link_to("Select", "/generation_z" , class: 'button-target') %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</br>
</br>
</br>

<h2 class="text-center"> Or take a look at all influencers available </h2>
</br>
</br>
</br>
<%= link_to "See all influencers", "/all_influencers", id: 'influencers', remote: true, class: 'btn btn-primary btn-lg btn-block' %>
</br>
</br>
</br>
</br>
</br>
<% else %>
<%= render 'shared/index_influencers' %>
<% end %>

app/views/influencers/index_complete.js.erb
$('#influencers').hide().after('<%= j render("index_complete") %>')

app/views/influencers/millennials.html.erb
<div class="wrapper">
  <%#= render 'shared/search_bar' %>
  <div class="influencer-header">
    <h1 class="text-center">Our Influencers</h1>
  </div>
  <div class="container">
    <div class="wrapper-index">
      <div class="cards-container-my-orders">
        <div class="row">
          <% @influencers.each do |influencer| %>
          <div class="col-xs-12 col-sm-4 col-lg-3">
            <div class="card">
              <%= link_to influencer_path(influencer) do %>
              <div class="card-picture"
              style="background: url('<%= influencer.photo %>')">
              <div class="card-title">
                <p class="influencer-name text-center"><%= influencer.first_name.titleize %> <%= influencer.last_name.titleize %></p>
              </div>
              <div class="card-footer">
                <p class="influencer-mediatype"><%= influencer.media_type.titleize %> <br />
                  <%= influencer.number_of_followers %> Followers</p>
                </div>
              </div>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/influencers/show.html.erb
  <div class="left-section">
    <% if @influencer.photo.model[:photo] == nil %>
    <div class="picture-show">
      <%= image_tag "http://s3.amazonaws.com/37assets/svn/765-default-avatar.png", size: "350x500", crop: :fill %>
      <% else %>
      <div class="picture-show">
        <%= cl_image_tag @influencer.photo, height: 500, width: 350 %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="right-section">
    <div id="influencer-name">
      <h1 class="text-center"> <%= @influencer.first_name %> <%= @influencer.last_name %></h1> <br />
      
    </div>

    <div id="social-media-identifier">
      <% if @influencer.media_type == "Instagram" %>
      <h3 class="text-center">Find the influencer on <%= @influencer.media_type.titleize %>: <%= @influencer.instagram_identifier %></h3>
      <h3 class="text-center">Followers: <%= @influencer.number_of_followers %></h3>
      <h3 class="text-center">Price for a story <%= humanized_money_with_symbol(@influencer.instagram_story_price) %></h3>
      <h3 class="text-center">Price for a post <%= humanized_money_with_symbol(@influencer.instagram_post_price) %></h3>
      <% else %>
      <h3 class="text-center">Find the influencer on <%= @influencer.media_type.titleize %>: <%= @influencer.youtube_identifier %></h3>
      <h3 class="text-center">Followers: <%= @influencer.number_of_followers %></h3>
      <h3 class="text-center">Price for a video <%= humanized_money_with_symbol(@influencer.youtube_vid_price) %></h3>
      <h3 class="text-center">Price for a reference <%= humanized_money_with_symbol(@influencer.youtube_ref_price) %></h3>
      <% end %>
    </div>

    <div id="influencer-influencer-levels">
      <h3 class="text-center"> Influence level: <%= @influencer.influence_level %></h3>
      <h3 class="text-center"> Global Score: <%= @influencer.global_score %> </h3>
    </div>

    <div id="influencer-misc">
      <h3 class="text-center">Age: <%= @influencer.age %></h3>
      <h3 class="text-center">Location: <%= @influencer.location %></h3>

    </div>
    <div class="proceed">
      <div class="button-submit">
       <%= link_to "Create a proposal", new_influencer_job_path(@influencer.id), class: "button-submit"  %>
     </div>
   </div>
 </div>
</div>