config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]
  root to: 'influencers#index'

  get '/my_jobs', to: 'jobs#index'
  get '/baby_boomers', to: 'influencers#baby_boomers'
  get '/generation_x', to: 'influencers#generation_x'
  get '/millennials', to: 'influencers#millennials'
  get '/generation_z', to: 'influencers#generation_z'
  get '/all_influencers', to: 'influencers#index_complete'



  resources :influencers, only: [:index, :index_complete, :show, :baby_boomers, :generation_x, :millennials, :generation_z] do
    resources :jobs, only: [:index, :show, :create, :new] do
          patch :update_job_state, on: :member
      resources :reviews, except: [:new, :show, :update]
    end
  end

  resources :orders, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
  end
end

app/models/job.rb
class Job < ApplicationRecord
  
  belongs_to :user, :class_name => "User",
  :foreign_key => :user_id, optional: true
  belongs_to :client, :class_name => "User", optional: true

  has_many :reviews, dependent: :destroy
  monetize :price_cents

  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @user = current_user
    if current_user.role == "client"
      @jobs = current_user.client_jobs
    else
      @jobs = current_user.influencer_jobs
    end
  end

  def new
    @job = Job.new
    @user = current_user
    @influencer = User.find(params[:influencer_id])
  end

  def show
    @user = current_user
    if @user.role == "influencer"
      @job = @user.influencer_jobs.find(params[:id])
    else
      @job = @user.client_jobs.find(params[:id])
      @influencer = @job.user
      @client = @job.client
    end
  end

  def update_job_state
    @user = current_user
    if @user.role == "influencer"
      @job = @user.influencer_jobs.find(params[:id])
      @job.update_attribute(:completed, true)
    else
      @job = @user.client_jobs.find(params[:id])
    end
  end

  def create
    # Defining all the info here -- best practice
    @influencer = User.find(params[:influencer_id])
    @user = current_user
    @job = Job.new(job_params)
    @job.user = @influencer # This defines the influencer that belongs to the job
    @job.client = @user # This defines the client that that belongs to the job

    # attempting to calculate the price
    if @influencer.media_type == "youtube"
      @job.price = (@influencer.youtube_vid_price * @job.youtube_vid) + (@influencer.youtube_ref_price * @job.youtube_ref)
    else
      @job.price = (@influencer.instagram_post_price * @job.instagram_post) + (@influencer.instagram_story_price * @job.instagram_story)
    end
    @job.save

    redirect_to new_order_path(@job)
  end

  private

  def job_params
    params.require(:influencer_job).permit(:instagram_post, :instagram_story, :youtube_vid, :youtube_ref, :description, :price )
  end
end

app/views/jobs/create.html.erb
<p><%= link_to 'Confirm order', influencer_job_order_payments_path(@job, @job.id) %></p>

app/views/jobs/index.html.erb
<%= render 'shared/my_jobs' %>

app/views/jobs/new.html.erb
<div class="container-job">
  <div class="row">
    <div class="job-header">
      <h1 class="text-center"> Proposal for <%= @influencer.first_name %></h1></br></br>
    </div>
      <!-- 
        Instagram divs  -->
        <% if @influencer.media_type == "instagram" %>
        <%= simple_form_for @job ,:url => {:action => :create, :controller => :jobs}, remote: true do |f| %>
        <label for="formGroupExampleInput">Instagram Stories</label>
        <div class="form-actions">
          <i class="fas fa-minus" onclick="decrease()"></i>
          <input name="influencer_job[instagram_story]" type="number" min="0" max="99" value="1" class="insta_stories" id="number" readonly>
          <i class="fas fa-plus" onclick="increase()"></i>

        </div>
        <label for="formGroupExampleInput">Instagram Posts</label></br>
        <div class="form-actions">
          <i class="fas fa-minus" onclick="decrease2()"></i>
          <input name="influencer_job[instagram_post]" type="number" min="0" max="99" value="1" class="insta_posts" id="number" readonly>
          <i class="fas fa-plus" onclick="increase2()"></i>
        </br>
      </br>

      <div class="form-group">
        <label for="exampleFormControlTextarea1">Job Description</label>
        <textarea class="form-control" name="influencer_job[description]" rows="3"></textarea>
      </div>
    </br>
</br>
</br>
<button class="button-propose" type="submit"> Submit your Proposal</button>

</div>
</div>
<% end %>
<% end %>
<!-- 
  Youtube divs  -->

  <% if @influencer.media_type == "youtube" %>
  <%= simple_form_for Job.new ,:url => {:action => :create, :controller => :jobs} do |f| %>
  <label for="formGroupExampleInput">YouTube Videos</label>
  <div class="form-actions">
    <i class="fas fa-minus" onclick="decrease3()"></i>
    <input name="influencer_job[youtube_vid]" type="number" min="0" max="99" value="1" class="youtube_vids" id="number" readonly>
    <i class="fas fa-plus" onclick="increase3()"></i>

  </div>
  <label for="formGroupExampleInput">YouTube References</label>
  <div class="form-actions">
    <i class="fas fa-minus" onclick="decrease4()"></i>
    <input name="influencer_job[youtube_ref]" type="number" min="0" max="99" value="1" class="youtube_refs" id="number" readonly>
    <i class="fas fa-plus" onclick="increase4()"></i>
  </br>
</br>
<div class="form-group">
  <label for="exampleFormControlTextarea1">Job Description</label>
  <textarea class="form-control" name="influencer_job[description]" rows="3"></textarea>
</div>
</br>
</br>
</br>
</div>
<button class="button-propose" type="submit"> Submit your Proposal</button>
<% end %>
<% end %>
</div>
</div>
</div>
</div>
</div>
</div>



<script>

// Counter for Instagram

function decrease() {
  let val = document.querySelector(".insta_stories");
  if(parseInt(val.value) > parseInt(val.min)) {
    val.value = parseInt(val.value) - 1;
  }
  return val;
}
function increase() {
  let val = document.querySelector(".insta_stories");
  if(parseInt(val.value) < parseInt(val.max)) {
    val.value = parseInt(val.value) + 1;
  }
  return val;
}


function decrease2() {
  let val = document.querySelector(".insta_posts");
  if(parseInt(val.value) > parseInt(val.min)) {
    val.value = parseInt(val.value) - 1;
  }
  return val;
}
function increase2() {
  let val = document.querySelector(".insta_posts");
  if(parseInt(val.value) < parseInt(val.max)) {
    val.value = parseInt(val.value) + 1;
  }
  return val;
}

// Counter for Youtube

function decrease3() {
  let val = document.querySelector(".youtube_vids");
  if(parseInt(val.value) > parseInt(val.min)) {
    val.value = parseInt(val.value) - 1;
  }
  return val;
}

function increase3() {
  let val = document.querySelector(".youtube_vids");
  if(parseInt(val.value) < parseInt(val.max)) {
    val.value = parseInt(val.value) + 1;
  }
  return val;
}

function decrease4() {
  let val = document.querySelector(".youtube_refs");
  if(parseInt(val.value) > parseInt(val.min)) {
    val.value = parseInt(val.value) - 1;
  }
  return val;
}
function increase4() {
  let val = document.querySelector(".youtube_refs");
  if(parseInt(val.value) < parseInt(val.max)) {
    val.value = parseInt(val.value) + 1;
  }
  return val;
}

</script>

app/views/jobs/show.html.erb
<% if current_user.role == "client" %>
<div class="container-my-jobs">
 <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
  <h1 class="text-center">Your order with <%= @influencer.first_name %></h1>
</br>
</br>
<div class="order-body">
  <% if @influencer.media_type == 'youtube' %>
  <h3 class="text-center"> Youtube Videos: <%= @job.youtube_vid %></h3>
  <h3 class="text-center"> Youtube References: <%= @job.youtube_ref %></h3>
  <% else %>
  <h3 class="text-center"> Instagram Posts: <%= @job.instagram_post %></h3>
  <h3 class="text-center"> Instagram Stories: <%= @job.instagram_story %></h3>
  <% end %>
  <h3 class="text-center"> Description: <%= @job.description %></h3>
  <h3 class="text-center"> Price Paid: <%= humanized_money_with_symbol(@job.price) %></h3>
</br>
</br>


<div class="go-back">
 <%= link_to "Back to orders", :back, class: "button-go-back" %>
</div>
</div>
<div class="job-done">
  <% if @job.completed? %>
  <button class="btn btn-success" disabled> Job completed</button>
  <% else %>
  <button class="btn btn-danger" disabled> Work in Progress </button>
  <% end %>
</div>

</br>
</br>
</br>
</div>
</div>
<% end %>

<% if current_user.role == "influencer" %>
<div class="container-my-jobs">
 <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
  <h1 class="text-center">Your order with <%= @job.client.first_name %></h1>
</br>
</br>
<div class="order-body">
  <% if current_user.media_type == 'youtube' %>
  <h3 class="text-center"> Youtube Videos: <%= @job.youtube_vid %></h3>
  <h3 class="text-center"> Youtube References: <%= @job.youtube_ref %></h3>
  <% else %>
  <h3 class="text-center"> Instagram Posts: <%= @job.instagram_post %></h3>
  <h3 class="text-center"> Instagram Stories: <%= @job.instagram_story %></h3>
  <% end %>
  <h3 class="text-center"> Description: <%= @job.description %></h3>
  <h3 class="text-center"> Price Received: <%= humanized_money_with_symbol(@job.price) %></h3>
</br>
</br>

<div class="go-back">
 <%= link_to "Back to orders", :back, class: "button-go-back" %>
</div>

<div class="job-done">
  <% if !@job.completed? %>
  <%= link_to "Mark the job as completed", update_job_state_influencer_job_path(@job), method: :patch, class: 'btn btn-default' %>
  <% else %>
  <button class="btn btn-success" disabled> Job completed</button>
  <% end %>
</div>
</div>
</br>
</br>
</br>
<% end %>

<%# raise %>