config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]
  root to: 'influencers#index'

  get '/my_jobs', to: 'jobs#index'
  get '/baby_boomers', to: 'influencers#baby_boomers'
  get '/generation_x', to: 'influencers#generation_x'
  get '/millennials', to: 'influencers#millennials'
  get '/generation_z', to: 'influencers#generation_z'
  get '/all_influencers', to: 'influencers#index_complete'



  resources :influencers, only: [:index, :index_complete, :show, :baby_boomers, :generation_x, :millennials, :generation_z] do
    resources :jobs, only: [:index, :show, :create, :new] do
          patch :update_job_state, on: :member
      resources :reviews, except: [:new, :show, :update]
    end
  end

  resources :orders, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id='footer_box'>

  <div class="logo">
    <!-- <%= image_tag 'logo', size: '50', class: "footer_icon" %> -->
    <i class="fab fa-apple"></i>
  </div>

  <div class="text_footer">
    <p>Contact/Information</p>
  </div>

  <div class="social_links">
    <ul class="list-inline">
      <li>
        <i class="fab fa-facebook-square"></i>
      </li>
      <li>
        <i class="fab fa-instagram"></i>
      </li>
      <li>
        <i class="fab fa-twitter"></i>
      </li>
    </ul>

  </div>

</div>

app/views/shared/_home_page.html.erb
<div class="wrapper-home">
  <div class="banner-home" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "social_media_home.jpg" %>');">
    <div class="banner-content">
      <h1>Grow your business with Influencers</h1>
      <div class="home-button">
        <%= link_to "Discover Influencers", influencers_path, class: "btn btn-success btn-lg"%>
      </div>
    </div>
  </div>

app/views/shared/_index_influencers.html.erb
<div class="wrapper-home">
  <div class="banner-home" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "influencer.jpg" %>');">
    <div class="banner-content">
      <h1 class="text-center">Become an Influencer</h1>
    </div>
  </div>

app/views/shared/_my_jobs.html.erb
<div class="container">
  <% if current_user.role == "client"  %>
  <div class="wrapper">
    <div class="cards-container-my-orders">
      <div class="row">
        <div class="my-orders-header">
          <h1 class="text-center">Your Orders</h1>
        </div>
        <% @jobs.each do |job| %>
        <div class="col-xs-12 col-sm-4 col-lg-4">
          <div class="card">
            <%= link_to influencer_job_path(job, job.id) do %>
            <div class="card-picture"
            style="background: url('<%= job.user.photo %>')">
            <div class="card-title">
              <p class="influencer-name text-center"><%= job.user.first_name.titleize %> <%= job.user.last_name.titleize %></p>
            </div>
            <div class="card-footer">
              <p class="influencer-mediatype"><%= job.user.media_type.titleize %> Content <br />
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
        <% end %>
      </div>
    </div>


<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-->

<% if current_user.role == "influencer"  %>
<div class="wrapper">
  <div class="cards-container-my-orders">
    <div class="row">
      <div class="my-orders-header">
        <h1 class="text-center">Your Orders</h1>
      </div>
      <% @jobs.each do |job| %>
      <div class="col-xs-12 col-sm-4 col-lg-4">
        <div class="card">
          <%= link_to influencer_job_path(job, job.id) do %>
          <div class="card-picture"
          style="background: url('<%= job.client.photo %>')">
          <div class="card-title">
            <p class="influencer-name text-center"><%= job.client.first_name.titleize %> <%= job.client.last_name.titleize %></p>
          </div>
          <div class="card-footer">
            <p class="influencer-mediatype"><%= job.user.media_type.titleize %> Content <br />
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
    

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <%= link_to "My Jobs", "/my_jobs", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
       <%= cl_image_tag current_user.photo, height: 50, width: 50, radius: :max , class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
       <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to user_path(current_user.id) do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "My Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
          <i class="fa fa-cog"></i>  <%= t(".settings", default: "Edit Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <% else %>
  <!-- Login link (when logged out) -->
  <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

  <% end %>
</div>

<% if user_signed_in? %>
<!-- Dropdown list appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="/my_jobs">My Jobs</a></li>
      <li><%= link_to "My Profile", user_path(current_user.id) %></a></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></a></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/shared/_payment.html.erb
<%= form_tag order_payments_path(@order) do %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="Job"
    data-email="<%= current_user.email %>"
    data-description="Job <%= @order.job_title %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>

<% end %>

app/views/shared/_search_bar.html.erb
<div class="search-influencers-wrapper">
  <div class="search-influencers">
    <%= form_tag influencers_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
      placeholder: "Find an influencer" %>
      <div class="button-submit-container">
        <%= submit_tag "Find", class: "search-button" %>
        <% end %>
      </div>
    </div>
  </div>