config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, :only => [:show]
  root to: 'influencers#index'

  get '/my_jobs', to: 'jobs#index'
  get '/baby_boomers', to: 'influencers#baby_boomers'
  get '/generation_x', to: 'influencers#generation_x'
  get '/millennials', to: 'influencers#millennials'
  get '/generation_z', to: 'influencers#generation_z'
  get '/all_influencers', to: 'influencers#index_complete'



  resources :influencers, only: [:index, :index_complete, :show, :baby_boomers, :generation_x, :millennials, :generation_z] do
    resources :jobs, only: [:index, :show, :create, :new] do
          patch :update_job_state, on: :member
      resources :reviews, except: [:new, :show, :update]
    end
  end

  resources :orders, only: [:show, :create, :new] do
    resources :payments, only: [:new, :create]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, :class_name => "User",
  :foreign_key => :user_id
  belongs_to :influencer, :class_name => "User"

  monetize :amount_cents
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @job = Job.last
    @user = current_user
    @influencer = @job.user
    @job.user = @influencer
    @job.client = @user
    @order  = Order.create!(job_title: @job.job_title, amount: @job.price, state: 'pending', user: current_user, influencer_id: @job.user.id)
  end

  def show
   @order = current_user.orders.where(state: 'paid').find(params[:id])
   @job = Job.last
   @user = current_user
   @influencer = @job.user
   @job.user = @influencer
   @job.client = @user
 end

 def create
  job = Job.find(params[:job_id])
  influencer = job.user
  order  = Order.create!(job_title: job.job_title, amount: job.price, state: 'pending', user: current_user, influencer_id: job.user.id)

  redirect_to new_order_payment_path(order)
end
end

app/views/orders/new.html.erb
<div class="container-confirmation">
  <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
    <h1 class="text-center">Confirmation of your order</h1>
    <h2 class="text-center">
    </br>
  </br>
  Order for <%= @influencer.first_name %> <%= @influencer.last_name %>
</h2>
<div class="order-body">
  <% if @influencer.media_type == 'youtube' %>
  <h3 class="text-center"> Youtube Videos: <%= @job.youtube_vid %></h3>
  <h3 class="text-center"> Youtube References: <%= @job.youtube_ref %></h3>
  <% else %>
  <h3 class="text-center"> Instagram Posts: <%= @job.instagram_post %></h3>
  <h3 class="text-center"> Instagram Stories: <%= @job.instagram_story %></h3>
  <% end %>
  <h3 class="text-center"> Description: <%= @job.description %></h3>
  <h3 class="text-center"> Price: <%= humanized_money_with_symbol(@job.price) %></h3>
</div>
</br>
</br>
</br>

<div class="button-confirm">
  
  <%= hidden_field_tag 'job_id', @job.id %>
  <%= render 'shared/payment' %>

</div>
</div>
</div>

app/views/orders/show.html.erb
<div class="container-confirmation">
  <div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
    <h1 class="text-center">Thank you for your order!</h1>
    <h2 class="text-center">
    </br>
  </br>
  Influencer's name: <%= @influencer.first_name %> <%= @influencer.last_name %>
</h2>
<div class="order-body">
  <% if @influencer.media_type == 'youtube' %>
  <h3 class="text-center"> Youtube Videos: <%= @job.youtube_vid %></h3>
  <h3 class="text-center"> Youtube References: <%= @job.youtube_ref %></h3>
  <% else %>
  <h3 class="text-center"> Instagram Posts: <%= @job.instagram_post %></h3>
  <h3 class="text-center"> Instagram Stories: <%= @job.instagram_story %></h3>
  <% end %>
  <h3 class="text-center"> Description: <%= @job.description %></h3>
  <h3 class="text-center"> Price: <%= humanized_money_with_symbol(@job.price) %></h3>
</div>
</br>
</br>
</br>
<div class="button-jobs">
  <%= link_to 'My Jobs', my_jobs_path, class:"button-confirm-jobs" %>
</div>
</div>
</div>